## Example config file - replace fields as required
##
dp-setup-path: "~/src/github.com/ONSdigital/dp-setup"                         # path to dp-setup             repo
dp-ci-path: "~/src/github.com/ONSdigital/dp-ci"                               # path to dp-ci                repo
dp-hierarchy-builder-path: "~/src/github.com/ONSdigital/dp-hierarchy-builder" # path to dp-hierarchy-builder repo
dp-code-list-scripts-path: "~/src/github.com/ONSdigital/dp-code-list-scripts" # path to dp-code-list-scripts repo

cmd:
  neo4j-url: bolt://localhost:7687
  mongo-url: localhost:27017
  mongo-dbs: # The mongo databases to be dropped when cleaning your CMD data
    - "imports"
    - "datasets"
    - "filters"
    - "codelists"
    - "test"
  hierarchies: # The hierarchies import scripts to run when importing CMD data
    - "admin-geography.cypher"
    - "cpih1dim1aggid.cypher"
    - "mid-year-pop-geography.cypher"

  codelists: # The codelist import scripts to run when importing CMD data
    - "cpih.yaml"
    - "mid-year-pop-est.yaml"

ssh-user: JamesHetfield

environments:
  - name: sandbox
    profile: dp-sandbox
    user: ubuntu       # required for all AWS-B envs and has to be ubuntu
    tags: [awsb]
  - name: staging
    profile: dp-staging
    user: ubuntu       # required for all AWS-B envs and has to be ubuntu
    tags: [awsb]
  - name: prod
    profile: dp-prod
    user: ubuntu       # required for all AWS-B envs and has to be ubuntu
    tags: [awsb,live]
  - name: ci
    profile: dp-ci
    user: ubuntu       # required for all AWS-B envs and has to be ubuntu
    tags: [awsb,ci]
  - name: concourse
    profile: develop
    user: ubuntu
    tags: [ci]
  - name: develop
    profile: develop
